
name: ci pipeline

on:
    push:
       branches: 
            - main

jobs:
    devik-sharma:
        runs-on: ubuntu-latest
         
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.8'

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt


            - name: setting up test cases
              run: echo "Setting up test cases"        
