name: ci pipeline

on:
    push:
       branches: 
            - main

jobs:
    python-app:
        runs-on: Ubuntu-latest
         
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                    python-version: '3.13'

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            - name: Running Flask App
              run: |
                    python app.py &
                    sleep 5
                    curl http://        


            - name: setting up test cases
              run: |
                   echo "Testing has been started"
                   curl http://127.0.0.1:5000        
                   echo "Testing has been completed"
